// <auto-generated />
using System;
using ControleEstoque.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ControleEstoque.Infra.Migrations
{
    [DbContext(typeof(MainContext))]
    partial class MainContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ControleEstoque.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataCriacao");

                    b.Property<DateTime>("DataNascimento");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<int>("NivelAcesso");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<string>("Senha")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            Id = new Guid("81d9ac1d-7795-4848-a61b-980be8802b48"),
                            DataCriacao = new DateTime(2020, 3, 12, 9, 53, 35, 969, DateTimeKind.Local).AddTicks(7887),
                            DataNascimento = new DateTime(2001, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fred@gmail.com",
                            NivelAcesso = 0,
                            Nome = "Fred",
                            Senha = "26d6a8ad97c75ffc548f6873e5e93ce475479e3e1a1097381e"
                        },
                        new
                        {
                            Id = new Guid("29494fb3-deba-4737-b499-91696ede988d"),
                            DataCriacao = new DateTime(2020, 3, 12, 9, 53, 35, 970, DateTimeKind.Local).AddTicks(9051),
                            DataNascimento = new DateTime(2001, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "gabriela@gmail.com",
                            NivelAcesso = 1,
                            Nome = "Gabriela",
                            Senha = "26d6a8ad97c75ffc548f6873e5e93ce475479e3e1a1097381e"
                        },
                        new
                        {
                            Id = new Guid("4669cc94-6139-4a54-9415-ab714892bcb1"),
                            DataCriacao = new DateTime(2020, 3, 12, 9, 53, 35, 970, DateTimeKind.Local).AddTicks(9120),
                            DataNascimento = new DateTime(2001, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ericka@gmail.com",
                            NivelAcesso = 2,
                            Nome = "Ericka",
                            Senha = "26d6a8ad97c75ffc548f6873e5e93ce475479e3e1a1097381e"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
